// Writes supabase/air_seed.sql: air_score + indicators.air for the existing hex_scores rows, WITHOUT recomputing the
// OSM scores (so it works without the full OSM extracts). Run after the air_score migration is applied.
// Usage: npx tsx scripts/air/compute.ts   (needs data/air/stations.json from scripts/air/build-air.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { cellToLatLng } from "h3-js";
import { airScore, interpolateAir, type AirFile } from "../../src/lib/data/air";
import { getDemoCells } from "../../src/lib/h3/grid";

const file = JSON.parse(readFileSync(process.env.AIR_FILE ?? "data/air/stations.json", "utf8")) as AirFile;
const cells = getDemoCells();
const rows: string[] = [];
for (const h3Index of cells) {
  const [lat, lng] = cellToLatLng(h3Index);
  const air = interpolateAir([lng, lat], file);
  if (air) rows.push(`('${h3Index}',${airScore(air)},'${JSON.stringify(air).replace(/'/g, "''")}'::jsonb)`);
}
writeFileSync(
  "supabase/air_seed.sql",
  `-- Generated by scripts/air/compute.ts from data/air/stations.json (${file.source}, snapshot ${file.fetched}).
update public.hex_scores h set air_score = v.score, indicators = coalesce(h.indicators, '{}'::jsonb) || jsonb_build_object('air', v.air)
from (values
${rows.join(",\n")}
) as v(h3_index, score, air) where h.h3_index = v.h3_index;
`,
);
console.log(rows.length, "of", cells.length, "cells have air data; wrote supabase/air_seed.sql");
