// Writes supabase/health_seed.sql: health_score + indicators.health for the existing hex_scores rows, WITHOUT
// recomputing the OSM scores. Run after the health_score migration is applied.
// Usage: npx tsx scripts/health/compute.ts   (needs data/health/features.json from scripts/health/build-features.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { cellToLatLng } from "h3-js";
import { HEALTH_KINDS, combineHealth, scoreHealth, type HealthFeaturesFile, type HealthIndicators } from "../../src/lib/data/health";
import { getDemoCells } from "../../src/lib/h3/grid";
import { rankScores } from "../../src/lib/data/safety";

const file = JSON.parse(readFileSync(process.env.HEALTH_FILE ?? "data/health/features.json", "utf8")) as HealthFeaturesFile;
const cells = getDemoCells();
const indicators: HealthIndicators[] = cells.map((h3) => {
  const [lat, lng] = cellToLatLng(h3);
  return scoreHealth([lng, lat], file);
});

// Per-kind score = percentile rank of the distance-weighted count among all cells; the combined score is their weighted mean.
const total = new Array<number>(cells.length).fill(0);
for (const k of HEALTH_KINDS) rankScores(indicators.map((i) => i[k].raw)).forEach((s, i) => (indicators[i][k].score = s));
indicators.forEach((ind, i) => {
  total[i] = combineHealth(Object.fromEntries(HEALTH_KINDS.map((k) => [k, ind[k].score as number])) as Record<(typeof HEALTH_KINDS)[number], number>);
});

const rows = cells.map((h3, i) => `('${h3}',${total[i]},'${JSON.stringify(indicators[i])}'::jsonb)`);
writeFileSync(
  "supabase/health_seed.sql",
  `-- Generated by scripts/health/compute.ts from data/health/features.json (${file.source}, ${file.fetched}).
update public.hex_scores h set health_score = v.score, indicators = coalesce(h.indicators, '{}'::jsonb) || jsonb_build_object('health', v.health)
from (values
${rows.join(",\n")}
) as v(h3_index, score, health) where h.h3_index = v.h3_index;
`,
);
console.log(rows.length, "cells; wrote supabase/health_seed.sql");
