// Writes supabase/health_seed.sql: health_score + indicators.health for the existing hex_scores rows, WITHOUT
// recomputing the OSM scores. Run after the health_score migration is applied.
// Usage: npx tsx scripts/health/compute.ts   (needs data/health/features.json from scripts/health/build-features.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { cellToLatLng } from "h3-js";
import { HEALTH_KINDS, combineHealth, scoreHealth, type HealthFeaturesFile, type HealthIndicators } from "../../src/lib/data/health";
import { getDemoCells } from "../../src/lib/h3/grid";
import { rankScores } from "../../src/lib/data/safety";

const file = JSON.parse(readFileSync(process.env.HEALTH_FILE ?? "data/health/features.json", "utf8")) as HealthFeaturesFile;
const cells = getDemoCells();
const indicators: HealthIndicators[] = cells.map((h3) => {
  const [lat, lng] = cellToLatLng(h3);
  return scoreHealth([lng, lat], file);
});

// Per-kind score = percentile rank of the distance-weighted count among all cells; the combined score is their weighted mean.
const total = new Array<number>(cells.length).fill(0);
for (const k of HEALTH_KINDS) rankScores(indicators.map((i) => i[k].raw)).forEach((s, i) => (indicators[i][k].score = s));
indicators.forEach((ind, i) => {
  total[i] = combineHealth(Object.fromEntries(HEALTH_KINDS.map((k) => [k, ind[k].score as number])) as Record<(typeof HEALTH_KINDS)[number], number>);
});

// Compact on purpose: per kind five numbers [raw, within500, within1000, nearestM (-1 = none), score], expanded to JSON by the SQL below.
const rows = cells.map((h3, i) => {
  const nums = HEALTH_KINDS.flatMap((k) => {
    const x = indicators[i][k];
    return [x.raw, x.within500, x.within1000, x.nearestM ?? -1, x.score as number];
  });
  return `('${h3}',${total[i]},array[${nums.join(",")}])`;
});
const kindsSql = HEALTH_KINDS.map((k) => `'${k}'`).join(",");
writeFileSync(
  "supabase/health_seed.sql",
  `-- Generated by scripts/health/compute.ts from data/health/features.json (${file.source}, ${file.fetched}).
-- Per kind (${HEALTH_KINDS.join(", ")}): raw, within500, within1000, nearestM (-1 = none), score.
update public.hex_scores h set health_score = v.score, indicators = coalesce(h.indicators, '{}'::jsonb) || jsonb_build_object('health', (
  select jsonb_object_agg(t.k, jsonb_build_object('raw', v.a[(t.n-1)*5+1], 'within500', v.a[(t.n-1)*5+2], 'within1000', v.a[(t.n-1)*5+3],
    'nearestM', nullif(v.a[(t.n-1)*5+4], -1), 'score', v.a[(t.n-1)*5+5]))
  from unnest(array[${kindsSql}]) with ordinality as t(k, n)
))
from (values
${rows.join(",\n")}
) as v(h3_index, score, a) where h.h3_index = v.h3_index;
`,
);
console.log(rows.length, "cells; wrote supabase/health_seed.sql");
